import { useEffect, useMemo, useState } from 'react';

const nav = [
    ['summary', '▦', 'Ringkasan'], ['orders', '🛒', 'Pesanan'], ['kitchen', '♨', 'Dapur'],
    ['catering', '⌒', 'Katering'], ['inventory', '▣', 'Bahan baku'], ['recipes', '▤', 'Menu & resep'], ['reports', '▥', 'Laporan'],
];
const rupiah = (value) => `Rp ${value.toLocaleString('id-ID')}`;
const go = (page) => { window.location.hash = page; };

function Button({ children, light = false, onClick }) {
    return <button className={`btn ${light ? 'light' : ''}`} onClick={onClick} type="button">{children}</button>;
}
function Badge({ children, tone = 'mint' }) { return <span className={`badge ${tone}`}>{children}</span>; }
function Search({ onChange, text = 'Cari...', value = '' }) { return <label className="search"><span>⌕</span><input onChange={(e) => onChange?.(e.target.value)} placeholder={text} value={value} /></label>; }
function Tabs({ options, setValue, value }) { return <div className="tabs">{options.map((x) => <button className={x === value ? 'active' : ''} key={x} onClick={() => setValue(x)} type="button">{x}</button>)}</div>; }
function Heading({ action, eyebrow = 'DATA CONTOH', subtitle, title }) { return <header className="heading"><div><small>{eyebrow}</small><h1>{title}</h1>{subtitle && <p>{subtitle}</p>}</div>{action}</header>; }
function Stat({ detail, icon, label, tone = '', value }) { return <article className="stat"><div><small>{label}</small><strong>{value}</strong><span>{detail}</span></div><i className={tone}>{icon}</i></article>; }
function Stats({ children }) { return <div className="stats">{children}</div>; }
function Panel({ children, className = '' }) { return <section className={`panel ${className}`}>{children}</section>; }

function Layout({ page, setOpen, children }) {
    const [open, setSidebar] = useState(false);
    useEffect(() => setOpen?.(setSidebar), [setOpen]);
    return <div className="shell"><aside className={`sidebar ${open ? 'open' : ''}`}><button className="close" onClick={() => setSidebar(false)} type="button">×</button><button className="brand" onClick={() => go('summary')} type="button"><b>×</b> Silih Asih ERP</button><nav>{nav.map(([id, icon, label]) => <button className={(page === 'new-order' ? 'orders' : page) === id ? 'active' : ''} key={id} onClick={() => { go(id); setSidebar(false); }} type="button"><i>{icon}</i>{label}</button>)}</nav><footer><b>♙</b><span>Budi Santoso<small>Pemilik</small></span></footer></aside>{open && <button className="backdrop" onClick={() => setSidebar(false)} type="button" />}<div className="main"><div className="topbar"><button className="hamburger" onClick={() => setSidebar(true)} type="button">☰</button><span>⌕</span><p>Cari menu, pesanan, atau bahan...</p><button type="button">♧</button><b>♙</b></div><main>{children}</main></div></div>;
}

const liveOrders = [
    ['#ORD-8421', 'Meja 4 - Rian', '2x Nasi Ayam Bakar, 1x Es Teh Manis', '10:14', 'Menunggu', 'yellow'],
    ['#ORD-8420', 'Meja 2 - Siska', '1x Soto Bandung, 1x Es Jeruk', '10:08', 'Dimasak', 'blue'],
    ['#ORD-8419', 'Takeaway - Dika', '3x Nasi Goreng Spesial', '09:55', 'Siap', 'green'],
];
function OrderTable({ rows = liveOrders }) { return <div className="table-wrap"><table><thead><tr><th>No. Pesanan</th><th>Pelanggan / Meja</th><th>Menu</th><th>Waktu</th><th>Status</th><th>Aksi</th></tr></thead><tbody>{rows.map((r) => <tr key={r[0]}><td className="id">{r[0]}</td><td>{r[1]}</td><td>{r[2]}</td><td>{r[3]}</td><td><Badge tone={r[5]}>{r[4]}</Badge></td><td><button className="detail" type="button">Detail</button></td></tr>)}</tbody></table></div>; }
function Summary() { const [filter, setFilter] = useState('Semua'); const rows = filter === 'Semua' ? liveOrders : liveOrders.filter((r) => r[4] === filter); return <><Heading action={<Button onClick={() => go('new-order')}>＋ Pesanan baru</Button>} eyebrow="OPERASIONAL HARI INI · 18 OKTOBER 2023" title="Ringkasan Operasional" /><Stats><Stat detail="Memerlukan pemrosesan dapur" icon="🛒" label="Pesanan aktif" value="12" /><Stat detail="150 porsi terjadwal" icon="⌒" label="Katering hari ini" value="3" /><Stat detail="Stok di bawah batas minimum" icon="△" label="Bahan perlu dibeli" tone="red" value="4" /></Stats><div className="overview"><Panel><div className="panel-head"><h2>Daftar Pesanan Aktif</h2><Tabs options={['Semua', 'Menunggu', 'Dimasak', 'Siap']} setValue={setFilter} value={filter} /></div><OrderTable rows={rows} /></Panel><div className="side-stack"><Panel className="attention"><div className="panel-head"><h2>ⓘ Perlu diperhatikan</h2><Badge tone="red">Stok Kritis</Badge></div><p>Bahan baku di bawah batas minimum operasional harian.</p>{[['Ayam potong', '2 kg tersisa', 'Defisit 3 kg'], ['Beras', '10 kg tersisa', 'Defisit 15 kg']].map((x) => <div className="stock" key={x[0]}><span><b>{x[0]}</b><small>Minimum operasional</small></span><span><b>{x[1]}</b><small>{x[2]}</small></span></div>)}<Button light onClick={() => go('inventory')}>▣ Buka bahan baku</Button></Panel><div className="next-event"><Badge>KATERING TERDEKAT</Badge><h3>Himpunan Mahasiswa</h3><p>50 porsi Nasi Kotak Ayam Bakar</p><small>◷ Siap jam 12:00</small></div></div></div></>; }

const allOrders = [
    ['#ORD-9482', 'Meja 04 · Bpk. Rizki', '2x Nasi Liwet Komplit, 1x Es Teh Manis', '11:42', 'Dimasak', 'green'],
    ['#ORD-9481', 'Fakultas Teknik UI · Ibu Siska', '50x Nasi Kotak Ayam Bakar', '11:15', 'Siap', 'green'],
    ['#ORD-9480', 'Meja 12 · Sdr. Dimas', '1x Soto Bandung, 1x Es Jeruk', '10:50', 'Selesai', 'gray'],
    ['#ORD-9479', 'Meja 02 · Ibu Ani', '3x Geprek Siliwangi, 3x Teh Botol', '10:35', 'Dibatalkan', 'red'],
    ['#ORD-9478', 'Rektorat Kampus · Dr. Hartono', '25x Prasmanan Rapat Senat', '09:10', 'Selesai', 'gray'],
];
function Orders() { const [q, setQ] = useState(''); const [type, setType] = useState('Semua'); const rows = allOrders.filter((r) => r.join(' ').toLowerCase().includes(q.toLowerCase())); return <><Heading action={<Button onClick={() => go('new-order')}>⊕ Pesanan Baru</Button>} eyebrow="MANAJEMEN OPERASIONAL · DATA CONTOH" title="Daftar Pesanan" /><Stats><Stat detail="↗ +12%" icon="🛒" label="Total Pesanan Hari Ini" value="48" /><Stat detail="Antrean aktif dapur" icon="♨" label="Sedang Dimasak" value="8" /><Stat detail="Menunggu diantar" icon="⌒" label="Siap Disajikan" value="5" /><Stat detail="↗ +8%" icon="▣" label="Pendapatan Harian" value="Rp 4.250K" /></Stats><Panel className="filters"><Search onChange={setQ} text="Cari No. Pesanan, Pelanggan, atau Menu..." value={q} /><Tabs options={['Semua', 'Langsung', 'Katering']} setValue={setType} value={type} /><input type="date" defaultValue="2023-10-25" /><div className="filter-pills">Status: {['Semua (48)', 'Menunggu (4)', 'Dimasak (8)', 'Siap (5)', 'Selesai (29)', 'Dibatalkan (2)'].map((x) => <Badge key={x}>{x}</Badge>)}</div></Panel><Panel className="table-panel"><OrderTable rows={rows} /><div className="pagination"><span>Menampilkan 1-{rows.length} dari 48 pesanan</span><span><button>‹</button><button className="active">1</button><button>2</button><button>3</button><button>›</button></span></div></Panel></>; }

const startBoard = { Menunggu: [['#ORD-8421', 'Meja 04 - Budi S.', '8 m lalu', ['2x Nasi Goreng Spesial', '1x Es Teh Manis']], ['#ORD-8422', 'Aula Kampus A', '12 m lalu', ['30x Paket Nasi Box Ayam Bakar', '30x Air Mineral Botol']], ['#ORD-8425', 'Meja 12 - Siti Rahma', '3 m lalu', ['1x Soto Bandung Spesial', '1x Nasi Putih Hangat']]], Dimasak: [['#ORD-8419', 'Meja 08 - Pak Joko', 'Dimasak 5m', ['3x Ayam Goreng Lengkuas', '3x Sayur Asem']], ['#ORD-8418', 'Rapat Rektorat Lt. 3', 'Dimasak 15m', ['15x Prasmanan Mini', '15x Es Buah']]], Siap: [['#ORD-8415', 'Meja 02 - Dian P.', 'Siap disajikan', ['1x Mie Goreng Tradisional', '1x Teh Hangat']]] };
function Kitchen() { const [board, setBoard] = useState(startBoard); const move = (from, card) => { const to = from === 'Menunggu' ? 'Dimasak' : 'Siap'; setBoard((b) => ({ ...b, [from]: b[from].filter((x) => x[0] !== card[0]), [to]: [...b[to], card] })); }; return <><div className="kds"><Badge>Sistem Tampilan Dapur (KDS)</Badge><span>● Live Sinkronisasi Aktif</span><Tabs options={['Semua Dapur', 'Station Utama', 'Katering']} setValue={() => {}} value="Semua Dapur" /></div><div className="kanban">{Object.entries(board).map(([status, cards]) => <section className={status.toLowerCase()} key={status}><header><h2>● {status} <Badge>{cards.length}</Badge></h2><small>{status === 'Menunggu' ? 'Antrian Masuk' : status === 'Dimasak' ? 'Proses Dapur' : 'Menunggu Saji'}</small></header>{cards.map((c) => <article className="ticket" key={c[0]}><div><span><small>{c[0]}</small><b>{c[1]}</b></span><Badge tone={status === 'Siap' ? 'green' : status === 'Dimasak' ? 'yellow' : 'red'}>{c[2]}</Badge></div><ul>{c[3].map((x) => <li key={x}>{x}<b>{x[0]}</b></li>)}</ul>{status !== 'Siap' ? <Button onClick={() => move(status, c)}>{status === 'Menunggu' ? '▷ Mulai Masak' : '✓ Tandai Siap'}</Button> : <p className="ready">Siap diantar / diambil</p>}</article>)}</section>)}</div></>; }

const foods = [['Nasi Ayam Bakar', 28000, 14, '🍗', 'Utama'], ['Nasi Goreng Spesial', 25000, 22, '🍳', 'Utama'], ['Soto Bandung', 30000, 3, '🍲', 'Utama'], ['Es Teh Manis', 5000, 85, '🥤', 'Minuman'], ['Es Jeruk', 7000, 40, '🍊', 'Minuman'], ['Paket Katering', 45000, 30, '🍱', 'Katering']];
function NewOrder() { const [kind, setKind] = useState('Makan di Tempat'); const [cart, setCart] = useState({}); const total = foods.reduce((s, f, i) => s + f[1] * (cart[i] || 0), 0); return <><div className="subbar"><Badge>DATA CONTOH</Badge><Tabs options={['Formulir Kasir', 'Antrean Aktif']} setValue={() => {}} value="Formulir Kasir" /></div><div className="entry"><div><Panel className="kind"><h2>Jenis Pesanan</h2><Tabs options={['Makan di Tempat', 'Takeaway', 'Katering']} setValue={setKind} value={kind} /></Panel><Search text="Cari menu berdasarkan nama atau bahan..." /><div className="food-grid">{foods.map((f, i) => <article className="food" key={f[0]}><div className="food-photo"><span>{f[3]}</span><Badge tone={f[2] < 5 ? 'red' : 'mint'}>Stok: {f[2]}</Badge></div><div><h3>{f[0]}</h3><b>{rupiah(f[1])}</b></div><p>Menu favorit Silih Asih dengan bahan pilihan...</p><footer><small>{f[2] < 5 ? 'Stok menipis' : 'Tersedia'}</small><span><button onClick={() => setCart({ ...cart, [i]: Math.max(0, (cart[i] || 0) - 1) })}>−</button>{cart[i] || 0}<button onClick={() => setCart({ ...cart, [i]: (cart[i] || 0) + 1 })}>＋</button></span></footer></article>)}</div></div><Panel className="receipt"><div className="panel-head"><h2>▤ Ringkasan Pesanan</h2><Badge>{kind}</Badge></div><label>Nomor Meja / Nama Pelanggan<input placeholder="Contoh: Meja 04 / Sdr. Rahmat" /></label><label>Catatan Pesanan<textarea placeholder="Contoh: Jangan terlalu pedas, kuah pisah..." /></label><div className="cart-lines">{Object.values(cart).some(Boolean) ? foods.map((f, i) => cart[i] ? <p key={f[0]}>{cart[i]}× {f[0]} <b>{rupiah(f[1] * cart[i])}</b></p> : null) : <p>Belum ada menu yang dipilih. Silakan tambah dari daftar sebelah kiri.</p>}</div><div className="totals"><p>Subtotal Item <b>{rupiah(total)}</b></p><p>Biaya Layanan / Pajak (10%) <b>{rupiah(total * .1)}</b></p><p>Total Sementara <b>{rupiah(total * 1.1)}</b></p></div><Button>✓ Simpan Pesanan</Button></Panel></div></>; }

const events = [['Perlu belanja', 'Hari Ini', 'Fakultas Teknik - Seminar Nasional', 200, 'red'], ['Bahan lengkap', 'Hari Ini', 'BEM Universitas - Rapat Pleno', 150, 'green'], ['Perlu belanja', 'Besok, 26 Okt', 'Dies Natalis Fakultas Ekonomi', 350, 'red'], ['Bahan lengkap', '28 Okt 2023', 'Pelepasan Wisuda Jurusan Arsitektur', 100, 'green']];
function Catering() { const [selected, setSelected] = useState(events[0]); return <><Heading action={<Button>＋ Tambah katering</Button>} eyebrow="DATA CONTOH · MANAJEMEN KATERING & ACARA" title="Jadwal Katering" /><Stats><Stat detail="3 pesanan aktif hari ini" icon="⌒" label="Total Porsi Hari Ini" value="450" /><Stat detail="Kurang: Daging Sapi, Santan" icon="🛒" label="Status Bahan Baku" value="2 Perlu Belanja" /><Stat detail="Siap masuk tahap pengerjaan" icon="✓" label="Bahan Lengkap" value="6 Acara" /><Stat detail="Bulan ini (8 katering)" icon="▣" label="Estimasi Pendapatan" value="Rp 38.5 Jt" /></Stats><div className="catering"><div>{events.map((e) => <button className={`event ${e[4]} ${selected === e ? 'selected' : ''}`} key={e[2]} onClick={() => setSelected(e)}><div><Badge tone={e[4]}>{e[0]}</Badge><Badge>{e[1]}</Badge><b>{e[3]} Porsi</b></div><h3>{e[2]}</h3><p>Pemesan: Dr. Ir. H. Mulyadi, M.T.</p><footer>♨ Nasi Kotak Premium (Rendang, Ayam Goreng)<b>{e[4] === 'red' ? '△ Kurang bahan' : '✓ Siap masak'}</b></footer></button>)}</div><Panel className="event-detail"><div className="panel-head"><h2>{selected[2]}</h2><Badge tone={selected[4]}>{selected[0]}</Badge></div><div className="info-box"><span><small>Informasi Pemesan</small><b>Dr. Mulyadi</b><small>+62 812-3456-7890</small></span><span><small>Jadwal Pengiriman</small><b>{selected[1]}</b><small>Pukul 11:30 WIB</small></span></div><h3>Menu & Porsi ({selected[3]} Porsi)</h3>{['Nasi Putih Pulen', 'Rendang Daging Sapi', 'Sambal Goreng Kentang', 'Kerupuk & Buah'].map((x) => <p className="list-row" key={x}>{x}<b>{selected[3]} porsi</b></p>)}<h3>Kesiapan Bahan Baku</h3><p className="shortage">ⓘ Daging Sapi Has <b>Kurang 4.5 kg</b></p><p className="shortage">ⓘ Santan Kental <b>Kurang 2 Liter</b></p><p className="available">✓ Beras Premium <b>Stok Cukup</b></p><h3>Rencana Pengerjaan Dapur</h3><ol><li>Belanja Kekurangan Bahan</li><li>Persiapan & Bumbu Dasar</li><li>Proses Masak & Packing</li></ol><Button>🛒 Belanja Bahan</Button></Panel></div></>; }

const stock = [['BRS-001', 'Beras Premium', '10 kg', 'Kritis'], ['AYM-002', 'Daging Ayam Segar', '2 kg', 'Kritis'], ['MNY-003', 'Minyak Goreng', '18 L', 'Aman'], ['STN-004', 'Santan Kental', '6 L', 'Menipis'], ['GUL-005', 'Gula Pasir', '12 kg', 'Aman']];
function Inventory() { return <><Heading action={<Button>＋ Catat Penerimaan</Button>} subtitle="Pantau stok fisik, alokasi pesanan, dan kebutuhan pembelian." title="Bahan Baku" /><Stats><Stat icon="▣" label="Total Bahan Aktif" value="42" /><Stat icon="△" label="Stok Kritis" tone="red" value="4" /><Stat icon="🛒" label="Dialokasikan" value="128 kg" /><Stat icon="✓" label="Penerimaan Hari Ini" value="6 item" /></Stats><Panel><div className="panel-head"><h2>Daftar Persediaan</h2><Search text="Cari bahan baku..." /></div><div className="table-wrap"><table><thead><tr><th>Kode</th><th>Nama Bahan</th><th>Stok Fisik</th><th>Status</th></tr></thead><tbody>{stock.map((x) => <tr key={x[0]}><td className="id">{x[0]}</td><td><b>{x[1]}</b></td><td>{x[2]}</td><td><Badge tone={x[3] === 'Aman' ? 'green' : x[3] === 'Kritis' ? 'red' : 'yellow'}>{x[3]}</Badge></td></tr>)}</tbody></table></div></Panel></>; }

const menus = [['🍛', 'Nasi Campur Silih Asih', 'Utama', 'Rp 28.000'], ['🍲', 'Soto Bandung Kuah Bening', 'Utama', 'Rp 25.000'], ['🥤', 'Es Teh Manis Melati', 'Minuman', 'Rp 5.000'], ['🥟', 'Tahu Goreng Crispy', 'Camilan', 'Rp 12.000']];
function Recipes() { const [sel, setSel] = useState(menus[0]); return <><Heading action={<Button>⊕ Tambah Menu / Resep Baru</Button>} subtitle="Kelola daftar hidangan, harga jual, status ketersediaan, serta takaran resep bahan baku." title="Manajemen Menu & Komposisi Resep" /><div className="policy"><b>ⓘ</b><span><h3>Kebijakan Riwayat Resep & Pesanan</h3><p>Perubahan komposisi resep tidak akan mengubah riwayat pesanan yang sudah diproses. Kalkulasi HPP mengikuti versi terbaru.</p></span></div><div className="recipes"><section><div className="panel-head"><h2>Daftar Hidangan & Ketersediaan</h2><Search text="Cari menu..." /></div><Panel className="menu-list">{menus.map((m, i) => <button className={sel === m ? 'selected' : ''} key={m[1]} onClick={() => setSel(m)}><i>{m[0]}</i><span><b>{m[1]}</b><small>{m[3]} · Resep: 1 Porsi</small></span><Badge>{m[2]}</Badge><em className={i < 3 ? 'on' : ''} /></button>)}</Panel></section><section><h2>Formulir Resep: {sel[1]}</h2><Panel className="recipe-form"><div className="yield"><label>Hasil Resep<input defaultValue="1" /></label><label>Tipe Takaran<select><option>Per Porsi</option></select></label></div><h3>Komposisi Bahan Baku <button>＋ Tambah Bahan</button></h3>{[['Beras Wangi', '150 gram'], ['Daging Ayam Fillet', '100 gram'], ['Minyak Goreng', '20 ml'], ['Bumbu Dasar Putih', '30 gram']].map((x) => <p className="ingredient" key={x[0]}>{x[0]}<input defaultValue={x[1].split(' ')[0]} /><small>{x[1].split(' ')[1]}</small><b>×</b></p>)}<p className="cost">Estimasi HPP Bahan / Porsi <b>Rp 11.450</b></p><Button>Simpan Perubahan Resep</Button></Panel></section></div></>; }

function Reports() { return <><Heading action={<Button>⇩ Ekspor Laporan</Button>} eyebrow="DATA CONTOH · PERIODE 01-31 OKT 2023" title="Laporan Operasional" /><Stats><Stat detail="Total transaksi sukses" icon="✓" label="Pesanan Selesai" value="1,428" /><Stat detail="Dibatalkan sistem/pelanggan" icon="×" label="Pesanan Dibatalkan" tone="red" value="34" /><Stat detail="Pesanan langsung" icon="◷" label="Waktu Tunggu Rata-rata" value="12.4 menit" /><Stat detail="Tepat waktu pengiriman" icon="⌒" label="Kepatuhan Katering" value="98.2 %" /></Stats><div className="charts"><Panel><div className="panel-head"><h2>Bahan Baku Terpakai & Terbuang</h2><small>Akumulasi Bulanan</small></div>{[['Beras Premium', 90], ['Daging Ayam Segar', 84], ['Minyak Goreng', 92], ['Sayuran Segar', 79]].map((x) => <div className="bar" key={x[0]}><p><b>{x[0]}</b><span>Terpakai: {x[1] * 5} kg | Terbuang: 12 kg</span></p><i><b style={{ width: `${x[1]}%` }} /></i></div>)}</Panel><Panel className="distribution"><h2>Distribusi Layanan</h2><p>Perbandingan volume pesanan</p><div className="donut"><b>1,462<small>Total Order</small></b></div><footer>● Langsung (75%)　<span>● Katering (25%)</span></footer></Panel></div><Panel><div className="panel-head"><h2>Detail Transaksi Harian</h2><Search text="Cari transaksi..." /></div><OrderTable rows={allOrders} /></Panel></>; }

const pages = { summary: Summary, orders: Orders, kitchen: Kitchen, 'new-order': NewOrder, catering: Catering, inventory: Inventory, recipes: Recipes, reports: Reports };
export default function DashboardApp() { const current = () => window.location.hash.slice(1) || 'summary'; const [page, setPage] = useState(current); useEffect(() => { const fn = () => setPage(current()); window.addEventListener('hashchange', fn); return () => window.removeEventListener('hashchange', fn); }, []); const Page = useMemo(() => pages[page] || Summary, [page]); return <Layout page={page}><Page /></Layout>; }
